version: '3.1'
services:
  web:
#    image: python:3.8
#    build: ./
    image: itaccounting
    build:
      context: ./
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    #platform: "linux/amd64"
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app/
    env_file: .env
  db:
    image: postgres:13
    restart: unless-stopped
    user: ${PSQL_UID}:${PSQL_GID}
    environment:
      POSTGRES_DB: ${PSQL_DB_NAME}
      POSTGRES_USER: ${PSQL_DB_USER}
      POSTGRES_PASSWORD: ${PSQL_DB_PASSWD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      -
        type: bind
        source: ./.db
        target: /var/lib/postgresql/data
