# Generated by Django 3.1.3 on 2020-11-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(default=None, max_length=32, null=True)),
                ('iban', models.CharField(default=None, max_length=29)),
                ('bank_number', models.CharField(default=None, max_length=6, null=True)),
                ('bank_name', models.CharField(default=None, max_length=64, null=True)),
            ],
        ),
    ]
