# Generated by Django 3.1.3 on 2020-12-26 19:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0008_auto_20201226_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=128, verbose_name='Contract number')),
                ('reference', models.CharField(blank=True, max_length=128, verbose_name='External reference')),
                ('sign_date', models.DateField(auto_now=True, verbose_name='Sign date')),
                ('closing_date', models.DateField(blank=True, default=datetime.date(2020, 12, 31), verbose_name='Contract closing date')),
                ('unlimited', models.BooleanField(verbose_name='Contract has invinite validity')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.company', verbose_name='My side')),
                ('company_signer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='signed_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Signer from my side')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Created by user')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.partner', verbose_name='Partner side')),
                ('partner_signer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.representative', verbose_name='Signer from partner side')),
            ],
            options={
                'db_table': 'contracts',
            },
        ),
    ]
