# Generated by Django 3.1.3 on 2020-12-26 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Contract short notes'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sign_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Sign date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='unlimited',
            field=models.BooleanField(verbose_name='Contract has infinite validity'),
        ),
    ]
