# Generated by Django 3.1.3 on 2020-12-26 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20201226_1932'),
        ('documents', '0002_auto_20201227_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(choices=[('invoice', 'Invoice'), ('completition', 'Completition certificate'), ('contract', 'Contract'), ('transaction', 'Bank transaction')], max_length=32, verbose_name='Sequence type')),
                ('step', models.PositiveSmallIntegerField(verbose_name='Step')),
                ('mask', models.CharField(default='{{ year }}/{{ month }}/{{ nr_month }}', max_length=255, verbose_name='Template in jinja format')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'db_table': 'sequence_setup',
            },
        ),
        migrations.CreateModel(
            name='SequenceStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Місяць')),
                ('number_for_month', models.IntegerField(verbose_name='Number in month')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Рік')),
                ('number_for_year', models.IntegerField(verbose_name='Number in year')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='documents.sequencesetup')),
            ],
            options={
                'db_table': 'sequence_storage',
            },
        ),
        migrations.AddConstraint(
            model_name='sequencesetup',
            constraint=models.UniqueConstraint(fields=('company', 'document'), name='uniq_company_document'),
        ),
    ]
