# Generated by Django 3.2.5 on 2021-08-03 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20201226_1932'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0004_auto_20210728_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=128, verbose_name='Contract number')),
                ('reference', models.CharField(blank=True, max_length=128, verbose_name='External reference')),
                ('sign_date', models.DateField(default=django.utils.timezone.now, verbose_name='Sign date')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.company', verbose_name='My side')),
                ('company_signer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='signed_completitions', to=settings.AUTH_USER_MODEL, verbose_name='Signer from my side')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_completitions', to=settings.AUTH_USER_MODEL, verbose_name='Created by user')),
                ('origin_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='completitions', to='documents.contract', verbose_name='Origin Contract')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.partner', verbose_name='Partner side')),
                ('partner_signer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.representative', verbose_name='Signer from partner side')),
            ],
            options={
                'db_table': 'completitions',
            },
        ),
        migrations.AlterField(
            model_name='sequencestorage',
            name='month',
            field=models.PositiveSmallIntegerField(default=8, verbose_name='Month'),
        ),
        migrations.CreateModel(
            name='CompletitionLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_hint', models.CharField(max_length=255, verbose_name='Product description')),
                ('product_uom_hint', models.CharField(max_length=16, verbose_name='UOM hint')),
                ('qty', models.FloatField(verbose_name='Product quantity')),
                ('price', models.FloatField(verbose_name='Unit price')),
                ('completition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='documents.completition', verbose_name='Completition certificate')),
            ],
            options={
                'db_table': 'completition_lines',
            },
        ),
    ]
