# Generated by Django 4.0.4 on 2022-07-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_completition_currency_contract_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total price'),
        ),
    ]
