# Generated by Django 4.0.4 on 2022-07-31 11:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20201226_1932'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0008_contract_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-issue_date']},
        ),
        migrations.AlterField(
            model_name='completition',
            name='company_signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='signed_completitions', to=settings.AUTH_USER_MODEL, verbose_name='З мого боку'),
        ),
        migrations.AlterField(
            model_name='completition',
            name='partner_signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.representative', verbose_name='Із сторони партнера'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='closing_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 12, 31), verbose_name='Дата закінчення контракту'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='company_signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='signed_contracts', to=settings.AUTH_USER_MODEL, verbose_name='З мого боку'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Замітки до контракта'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='partner_signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.representative', verbose_name='Із сторони партнера'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='unlimited',
            field=models.BooleanField(verbose_name='Немає кінцевої дати'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='signed_invoices', to=settings.AUTH_USER_MODEL, verbose_name='З мого боку'),
        ),
        migrations.AlterField(
            model_name='sequencesetup',
            name='document',
            field=models.CharField(choices=[('invoice', 'Рахунок'), ('completition', 'Акт виконаних робіт'), ('contract', 'Договір'), ('transaction', 'Банківська транзакція')], max_length=32, verbose_name='Тип нумератора'),
        ),
        migrations.AlterField(
            model_name='sequencesetup',
            name='step',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Крок'),
        ),
        migrations.AlterField(
            model_name='sequencestorage',
            name='month',
            field=models.PositiveSmallIntegerField(default=7, verbose_name='Місяць'),
        ),
        migrations.AlterField(
            model_name='sequencestorage',
            name='year',
            field=models.PositiveSmallIntegerField(default=2022, verbose_name='Рік'),
        ),
        migrations.CreateModel(
            name='ContractExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=128, verbose_name='Посилання')),
                ('sign_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата підписання')),
                ('price', models.FloatField(default=0.0, verbose_name='Ціна')),
                ('notes', models.TextField(blank=True, verbose_name='Short notes')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='documents.contract', verbose_name='Договір')),
            ],
        ),
    ]
