# Generated by Django 4.0.6 on 2022-08-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencestorage',
            name='month',
            field=models.PositiveSmallIntegerField(default=8, verbose_name='Місяць'),
        ),
    ]
