# Generated by Django 4.1.3 on 2023-10-18 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0011_completition_origin_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completition",
            name="currency",
            field=models.CharField(
                choices=[
                    ("UAH", "грн."),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                    ("CHF", "CHF"),
                ],
                default="UAH",
                max_length=3,
                verbose_name="Currency",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="closing_date",
            field=models.DateField(
                blank=True,
                default=datetime.date(2023, 12, 31),
                verbose_name="Дата закінчення контракту",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="currency",
            field=models.CharField(
                choices=[
                    ("UAH", "грн."),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                    ("CHF", "CHF"),
                ],
                default="UAH",
                max_length=3,
                verbose_name="Currency",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="currency",
            field=models.CharField(
                choices=[
                    ("UAH", "грн."),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                    ("CHF", "CHF"),
                ],
                default="UAH",
                max_length=3,
                verbose_name="Currency",
            ),
        ),
        migrations.AlterField(
            model_name="sequencestorage",
            name="month",
            field=models.PositiveSmallIntegerField(default=10, verbose_name="Місяць"),
        ),
        migrations.AlterField(
            model_name="sequencestorage",
            name="year",
            field=models.PositiveSmallIntegerField(default=2023, verbose_name="Рік"),
        ),
    ]
