# Generated by Django 3.1.3 on 2020-11-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20201125_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='available_companies',
            field=models.ManyToManyField(db_table='employee_companies', related_name='managing_users', to='company.Company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_line_1',
            field=models.CharField(max_length=128, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_line_2',
            field=models.CharField(max_length=128, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_line_3',
            field=models.CharField(max_length=128, verbose_name='Address 3'),
        ),
        migrations.AlterField(
            model_name='company',
            name='itn',
            field=models.CharField(max_length=16, verbose_name='Personal taxing number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_first',
            field=models.CharField(max_length=64, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_last',
            field=models.CharField(max_length=64, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_middle',
            field=models.CharField(max_length=64, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='reg',
            field=models.CharField(max_length=32, verbose_name='Taxing registration number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Current e-mail cannot be registered'}, max_length=254, unique=True, verbose_name='email адреса'),
        ),
    ]
