# Generated by Django 3.1.3 on 2020-12-25 16:48

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20201128_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tel_fax',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='company',
            name='tel_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_line_3',
            field=models.CharField(blank=True, max_length=128, verbose_name='Address 3'),
        ),
    ]
