# Generated by Django 3.1.3 on 2020-12-25 21:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20201225_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='tel_fax',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='partner',
            name='tel_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_line_1',
            field=models.CharField(max_length=128, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_line_2',
            field=models.CharField(max_length=128, verbose_name='Address line 2'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_line_3',
            field=models.CharField(blank=True, max_length=128, verbose_name='Address line 3'),
        ),
        migrations.AlterField(
            model_name='company',
            name='itn',
            field=models.CharField(max_length=16, verbose_name='Personal tax number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='reg',
            field=models.CharField(max_length=32, verbose_name='Legacy registration number'),
        ),
    ]
