# Generated by Django 3.1.3 on 2020-12-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20201225_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='partner',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='partner',
            name='address_line_3',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='partner',
            name='itn',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='partner',
            name='reg',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='partner',
            name='representative_name_first',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='partner',
            name='representative_name_last',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='partner',
            name='representative_name_middle',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='partner',
            name='representative_position',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
