# Generated by Django 3.1.3 on 2020-12-26 17:14

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20201226_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='representative_name_first',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='representative_name_last',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='representative_name_middle',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='representative_position',
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=64)),
                ('first_name', models.CharField(blank=True, max_length=64)),
                ('middle_name', models.CharField(blank=True, max_length=64)),
                ('position', models.CharField(blank=True, max_length=16)),
                ('email', models.EmailField(blank=True, error_messages={'unique': 'Current e-mail cannot be registered'}, max_length=254, unique=True, verbose_name='E-mail адреса')),
                ('tel_mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('tel_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_signer', models.BooleanField(default=False, verbose_name='Granted to sign documents')),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representatives', to='company.partner')),
            ],
            options={
                'db_table': 'partners_represenatives',
                'unique_together': {('partner', 'is_signer')},
            },
        ),
    ]
