# Generated by Django 3.1.3 on 2020-12-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20201226_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'Current e-mail cannot be registered'}, max_length=254, null=True, unique=True, verbose_name='E-mail адреса'),
        ),
    ]
