# Generated by Django 4.0.6 on 2022-08-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20201226_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_foreign',
            field=models.BooleanField(default=False),
        ),
    ]
